#define KEY_Esc                0x011B
#define KEY_1                  0x0231
#define KEY_2                  0x0332
#define KEY_3                  0x0433
#define KEY_4                  0x0534
#define KEY_5                  0x0635
#define KEY_6                  0x0736
#define KEY_7                  0x0837
#define KEY_8                  0x0938
#define KEY_9                  0x0A39
#define KEY_0                  0x0B30

#define KEY_1_NUM              0x4f31
#define KEY_2_NUM              0x5032
#define KEY_3_NUM              0x5133
#define KEY_4_NUM              0x4b34
#define KEY_5_NUM              0x4c35
#define KEY_6_NUM              0x4d36
#define KEY_7_NUM              0x4737
#define KEY_8_NUM              0x4838
#define KEY_9_NUM              0x4939
#define KEY_0_NUM              0x5230

#define KEY_minus              0x0C2D
#define KEY_equal              0x0D3D
#define KEY_BkSp               0x0E08
#define KEY_Tab                0x0F09
#define KEY_q                  0x1071
#define KEY_w                  0x1177
#define KEY_e                  0x1265
#define KEY_r                  0x1372
#define KEY_t                  0x1474
#define KEY_y                  0x1579
#define KEY_u                  0x1675
#define KEY_i                  0x1769
#define KEY_o                  0x186F
#define KEY_p                  0x1970
#define KEY_left_sq_bra        0x1A5B /* left square bracket */
#define KEY_right_sq_bra       0x1B5D /* right square bracket */
#define KEY_Cr                 0x1C0D
#define KEY_a                  0x1E61
#define KEY_s                  0x1F73
#define KEY_d                  0x2064
#define KEY_f                  0x2166
#define KEY_g                  0x2267
#define KEY_h                  0x2368
#define KEY_j                  0x246A
#define KEY_k                  0x256B
#define KEY_l                  0x266C
#define KEY_semicolon          0x273B /* semicolon */
#define KEY_apostrophe         0x2827 /* apostrophe */
#define KEY_accent             0x2960 /* grave accent */
#define KEY_backslash          0x2B5C /* back slash */
#define KEY_z                  0x2C7A
#define KEY_x                  0x2D78
#define KEY_c                  0x2E63
#define KEY_v                  0x2F76
#define KEY_b                  0x3062
#define KEY_n                  0x316E
#define KEY_m                  0x326D
#define KEY_comma              0x332C
#define KEY_period             0x342E
#define KEY_slash              0x352F
#define KEY_Gray_star          0x372A
#define KEY_Space              0x3920
#define KEY_F1                 0x3B00
#define KEY_F2                 0x3C00
#define KEY_F3                 0x3D00
#define KEY_F4                 0x3E00
#define KEY_F5                 0x3F00
#define KEY_F6                 0x4000
#define KEY_F7                 0x4100
#define KEY_F8                 0x4200
#define KEY_F9                 0x4300
#define KEY_F10                0x4400
#define KEY_Home               0x4700 /* White */
#define KEY_Up                 0x4800 /* White Arrow */
#define KEY_PgUp               0x4900 /* White */
#define KEY_Gray_minus         0x4A2D /* minus */
#define KEY_Left               0x4B00 /* White Arrow */
#define KEY_Right              0x4D00 /* White Arrow */
#define KEY_Gray_plus          0x4E2B /* plus */
#define KEY_End                0x4F00 /* White */
#define KEY_Down               0x5000 /* White Arrow */
#define KEY_PgDn               0x5100 /* White */
#define KEY_Ins                0x5200 /* White */
#define KEY_Del                0x5300 /* White */
#define KEY_Shift_Esc          0x011B
#define KEY_exclamation        0x0221
#define KEY_at                 0x0340
#define KEY_number             0x0423
#define KEY_dollar             0x0524
#define KEY_procent            0x0625
#define KEY_caret              0x075E
#define KEY_and                0x0826
#define KEY_star               0x092A /* white */
#define KEY_left_bra           0x0A28
#define KEY_right_bra          0x0B29
#define KEY__                  0x0C5F
#define KEY_plus               0x0D2B /* white plus */
#define KEY_Shift_BkSp         0x0E08
#define KEY_Shift_Tab          0x0F00 /* Backtab */
#define KEY_Q                  0x1051
#define KEY_W                  0x1157
#define KEY_E                  0x1245
#define KEY_R                  0x1352
#define KEY_T                  0x1454
#define KEY_Y                  0x1559
#define KEY_U                  0x1655
#define KEY_I                  0x1749
#define KEY_O                  0x184F
#define KEY_P                  0x1950
#define KEY_left_acolade       0x1A7B
#define KEY_right_acolade      0x1B7D
#define KEY_Shift_Cr           0x1C0D
#define KEY_A                  0x1E41
#define KEY_S                  0x1F53
#define KEY_D                  0x2044
#define KEY_F                  0x2146
#define KEY_G                  0x2247
#define KEY_H                  0x2348
#define KEY_J                  0x244A
#define KEY_K                  0x254B
#define KEY_L                  0x264C
#define KEY_colon              0x273A
#define KEY_quote              0x2822
#define KEY_tilda              0x297E
#define KEY_or                 0x2B7C
#define KEY_Z                  0x2C5A
#define KEY_X                  0x2D58
#define KEY_C                  0x2E43
#define KEY_V                  0x2F56
#define KEY_B                  0x3042
#define KEY_N                  0x314E
#define KEY_M                  0x324D
#define KEY_left_ang_bra       0x333C
#define KEY_right_ang_bra      0x343E
#define KEY_question_mark      0x353F
#define KEY_Shift_Space        0x3920
#define KEY_Shift_F1           0x5400
#define KEY_Shift_F2           0x5500
#define KEY_Shift_F3           0x5600
#define KEY_Shift_F4           0x5700
#define KEY_Shift_F5           0x5800
#define KEY_Shift_F6           0x5900
#define KEY_Shift_F7           0x5A00
#define KEY_Shift_F8           0x5B00
#define KEY_Shift_F9           0x5C00
#define KEY_Shift_F10          0x5D00
#define KEY_Shift_7            0x4737 /* number pad */
#define KEY_Shift_8            0x4838 /* number pad */
#define KEY_Shift_9            0x4939 /* number pad */
#define KEY_Shift_Gray_minus   0x4A2D
#define KEY_Shift_4            0x4B34 /* number pad */
#define KEY_Shift_5            0x4C35 /* number pad */
#define KEY_Shift_6            0x4D36 /* number pad */
#define KEY_Shift_Gray_plus    0x4E2B
#define KEY_Shift_1            0x4F31
#define KEY_Shift_2            0x5032 /* number pad */
#define KEY_Shift_3            0x5133 /* number pad */
#define KEY_Shift_0            0x5230 /* number pad */
#define KEY_Shift_period       0x532E /* number pad */
#define KEY_Ctrl_Esc           0x011B /* number pad */
#define KEY_Ctrl_2             0x0300
#define KEY_Ctrl_6             0x071E /* NUL */
#define KEY_Ctrl_minus         0x0C1F /* RS */
#define KEY_Ctrl_BkSp          0x0E7F
#define KEY_Ctrl_q             0x1011 /* DEL */
#define KEY_Ctrl_w             0x1117 /* DC1 */
#define KEY_Ctrl_e             0x1205 /* ETB */
#define KEY_Ctrl_r             0x1312 /* ENQ */
#define KEY_Ctrl_t             0x1414 /* DC2 */
#define KEY_Ctrl_y             0x1519 /* DC4 */
#define KEY_Ctrl_u             0x1615 /* EM */
#define KEY_Ctrl_i             0x1709 /* NAK */
#define KEY_Ctrl_o             0x180F /* HT */
#define KEY_Ctrl_p             0x1910 /* SI */
#define KEY_Ctrl_left_sq_bra   0x1A1B /* DEL */
#define KEY_Ctrl_right_sq_bra  0x1B1D /* ESC */
#define KEY_Ctrl_Cr
#define KEY_Ctrl_a             0x1E01 /* LF */
#define KEY_Ctrl_s             0x1F13 /* SOH */
#define KEY_Ctrl_d             0x2004 /* DC3 */
#define KEY_Ctrl_f             0x2106 /* EOT */
#define KEY_Ctrl_g             0x2207 /* ACK */
#define KEY_Ctrl_h             0x2308 /* BEL */
#define KEY_Ctrl_j             0x240A /* BkSp */
#define KEY_Ctrl_k             0x250B /* LF */
#define KEY_Ctrl_l             0x260C /* VT */
#define KEY_Ctrl_backslash     0x2B1C /* FF */
#define KEY_Ctrl_z             0x2C1A /* FS */
#define KEY_Ctrl_x             0x2D18 /* SUB */
#define KEY_Ctrl_c             0x2E03 /* CAN */
#define KEY_Ctrl_v             0x2F16 /* ETX */
#define KEY_Ctrl_b             0x3002 /* SYN */
#define KEY_Ctrl_n             0x310E /* STX */
#define KEY_Ctrl_m             0x320D /* SO */
#define KEY_Ctrl_Space         0x3920 /* CR */
#define KEY_Ctrl_F1            0x5E00
#define KEY_Ctrl_F2            0x5F00
#define KEY_Ctrl_F3            0x6000
#define KEY_Ctrl_F4            0x6100
#define KEY_Ctrl_F5            0x6200
#define KEY_Ctrl_F6            0x6300
#define KEY_Ctrl_F7            0x6400
#define KEY_Ctrl_F8            0x6500
#define KEY_Ctrl_F9            0x6600
#define KEY_Ctrl_F10           0x6700
#define KEY_Ctrl_Home          0x7700
#define KEY_Ctrl_PgUp          0x8400 /* White */
#define KEY_Ctrl_Left          0x7300 /* White */
#define KEY_Ctrl_Right         0x7400 /* White Arrow */
#define KEY_Ctrl_End           0x7500 /* White Arrow */
#define KEY_Ctrl_PgDn          0x7600 /* White */
#define KEY_Alt_1              0x7800 /* White */
#define KEY_Alt_2              0x7900
#define KEY_Alt_3              0x7A00
#define KEY_Alt_4              0x7B00
#define KEY_Alt_5              0x7C00
#define KEY_Alt_6              0x7D00
#define KEY_Alt_7              0x7E00
#define KEY_Alt_8              0x7F00
#define KEY_Alt_9              0x8000
#define KEY_Alt_0              0x8100
#define KEY_Alt_0              0x8100
#define KEY_Alt_minus          0x8200
#define KEY_Alt_equal          0x8300
#define KEY_Alt_q              0x1000
#define KEY_Alt_w              0x1100
#define KEY_Alt_e              0x1200
#define KEY_Alt_r              0x1300
#define KEY_Alt_t              0x1400
#define KEY_Alt_y              0x1500
#define KEY_Alt_u              0x1600
#define KEY_Alt_i              0x1700
#define KEY_Alt_o              0x1800
#define KEY_Alt_p              0x1900
#define KEY_Alt_a              0x1E00
#define KEY_Alt_s              0x1F00
#define KEY_Alt_d              0x2000
#define KEY_Alt_f              0x2100
#define KEY_Alt_g              0x2200
#define KEY_Alt_h              0x2300
#define KEY_Alt_j              0x2400
#define KEY_Alt_k              0x2500
#define KEY_Alt_l              0x2600
#define KEY_Alt_z              0x2C00
#define KEY_Alt_x              0x2D00
#define KEY_Alt_c              0x2E00
#define KEY_Alt_v              0x2F00
#define KEY_Alt_b              0x3000
#define KEY_Alt_n              0x3100
#define KEY_Alt_m              0x3200
#define KEY_Alt_Space          0x3920
#define KEY_Alt_F1             0x6800
#define KEY_Alt_F2             0x6900
#define KEY_Alt_F3             0x6A00
#define KEY_Alt_F4             0x6B00
#define KEY_Alt_F5             0x6C00
#define KEY_Alt_F6             0x6D00
#define KEY_Alt_F7             0x6E00
#define KEY_Alt_F8             0x6F00
#define KEY_Alt_F9             0x7000
#define KEY_Alt_F10            0x7100
